sshCopyID

diff --git a/kubecsv b/kubecsv
--- a/kubecsv
+++ b/kubecsv
@@ -722,7 +722,7 @@ function sshCopyID() {
   if [ "$PRIVATE_KEY" == "" ]; then echo "-- ERROR: PRIVATE_KEY is empty " >&3 ; return 1; fi
 
   if [ ! -f $PRIVATE_KEY ]; then
-    echo "-- $PRIVATE_KEY no found. Generating new keys" >&3
+    echo "-- $PRIVATE_KEY not found. Generating new keys" >&3
     mkdir -p "$(dirname $PRIVATE_KEY)"
     ssh-keygen -t rsa -b 4096 -C "k8s" -f "$PRIVATE_KEY" -N ""
   else
@@ -1407,10 +1407,9 @@ while ! IS_ALL_NODES_ONLINE; do
   readArrayVar NODE_ARRAY "Please entre kubernetes cluster's nodes IP addresses the first one is the master (seperate IPs with SPACE)" "$(IFS=' ' ; echo "$NODE_ARRAY_DEFAULT" )"
 done
 readVar SSH_USERNAME "$SSH_USERNAME_DEFAULT" "Please entre the SSH username" 1
-while [ ! -f "$PRIVATE_KEY" ]; do
+while ! sshCopyID; do
   PRIVATE_KEY="$PRIVATE_KEY_DEFAULT"
   readVar PRIVATE_KEY "$PRIVATE_KEY_DEFAULT" "Please enter the absolute path for your private key. It will be created if does not exist. The default value is recommended"
-  sshCopyID
 done
 if [ ! -f "$KUBECONFIG" ]; then
   KUBECONFIG="$KUBECONFIG_DEFAULT"
