$HOSTNAME logging

diff --git a/kubecsv b/kubecsv
--- a/kubecsv
+++ b/kubecsv
@@ -214,10 +214,10 @@ function WAIT_ALL_NODES_ONLINE() {
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     host="${NODE_ARRAY[$i]}"
     while ! ping -c1 $host &>/dev/null; do
-      echo "-- NODE $i: Waiting to be online (ping ${NODE_ARRAY[$i]})" >&3
+      echo "-- Waiting for $host to be online" >&3
       sleep 5
     done
-    echo "-- NODE $i: Online" >&3
+    echo "-- $host is online" >&3
   done
 }
 
@@ -295,9 +295,9 @@ ____EOF____
 #######################################
 #######################################
 function SWAPRemoval() {
+  echo "-- Removing SWAP and rebooting if needed on all nodes" >&3
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     (
-      echo "-- NODE $i: Removing SWAP and rebooting if needed" >&3
       ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
@@ -554,7 +554,7 @@ clusterDomain: cluster.local
 resolvConf: /etc/resolv.conf" > 'kubeletconfiguration0+merge.yaml'
   fi
 fi
-echo "-- Node $i: Upgrading kubelet configuration"
+echo "-- $HOSTNAME :Upgrading kubelet configuration"
 kubeadm upgrade node phase kubelet-config --patches ./
 systemctl restart kubelet
 ____EOF____
@@ -599,23 +599,23 @@ function unD() {
     ) &
     wait $!
 
+    echo "-- Deleting leftover NICs, and cni files on all nodes" >&3
     for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
-      echo "-- Node $i: Deleting DHCP demon, leftover NICs, and cni files" >&3
       (
       ssh -i "$MY_PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"${NODE_ARRAY[i]}" i=$i bash <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
 
-echo "-- Node $i: deleting leftover NICs"
+echo "-- $HOSTNAME :deleting leftover NICs"
 for nic in $(ip link show | grep -e cni -e flannel | awk -F@ '{print $1}' | awk '{print $2}'); do
   ip link set $nic down
   ip link delete $nic
 done
 
-echo "-- Node $i: Force stopping cni demon"
+echo "-- $HOSTNAME :Force stopping cni demon"
 kill -9 $(ps aux | grep "/opt/cni/bin" | awk '{print $2}')
 
-echo "-- Node $i: Deleting cni files"
+echo "-- $HOSTNAME :Deleting cni files"
 rm -rf /run/flannel
 rm -rf /opt/cni
 rm -rf /run/cni
@@ -661,9 +661,9 @@ function sshCopyID() {
     echo "-- copying public key to $IP " >&3
     ssh-copy-id -o LogLevel=QUIET -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"$IP" 1>&3
     if [[ $? -eq 0 ]]; then
-      echo "-- NODE $i: ssh-copy-id successful"
+      echo "-- ssh-copy-id for $IP is successful"
     else
-      echo "-- NODE $i: ssh-copy-id failed"
+      echo "-- ssh-copy-id failed for $IP"
       return 1
     fi
   done
@@ -738,24 +738,24 @@ function step0() {
     done
   fi
 
+  echo "-- Uninstalling (inc. reset kubeadm, firewall, files, NICs) on all nodes" >&3
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     (
-      echo "-- NODE $i: Uninstalling (inc. reset kubeadm, firewall, files, NICs) ..." >&3
       ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
 
 echo "-- Uninstalling in Node $i"
 if command -v kubeadm &> /dev/null; then
-    echo "-- NODE $i: Reseting k8s"
+    echo "-- $HOSTNAME :Reseting k8s"
     kubeadm reset --cleanup-tmp-dir --force 
 fi
 
-echo "-- NODE $i: Clearing firewall"
+echo "-- $HOSTNAME :Clearing firewall"
 iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
 ipvsadm --clear 
 
-echo "-- NODE $i: Uninstalling k8s (kubelet, kubeadm, and containerd)"
+echo "-- $HOSTNAME :Uninstalling k8s (kubelet, kubeadm, and containerd)"
 apt-mark unhold kubelet kubeadm kubectl docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
 for pkg in kubectl kubeadm kubelet ipvsadm docker-ce docker-ce-cli docker.io containerd.io docker-doc docker-build-plugin docker-compose-plugin docker-compose docker-compose-v2 podman-docker containerd runc temurin-21-jre containerd; do
     apt purge -y --allow-change-held-packages $pkg 
@@ -763,7 +763,7 @@ done
 systemctl stop $(systemctl -l | grep kube) 
 systemctl disable $(systemctl -l | grep kube) 
 
-echo "-- NODE $i: Removing gpg and source lists of kubernetes and adoptium"
+echo "-- $HOSTNAME :Removing gpg and source lists of kubernetes and adoptium"
 rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
 rm -f /etc/apt/trusted.gpg.d/adoptium.gpg
 rm -f /etc/apt/sources.list.d/kubernetes.list
@@ -771,7 +771,7 @@ rm -f /etc/apt/sources.list.d/adoptium.list
 apt update -y 
 
 systemctl daemon-reload 
-echo "-- NODE $i: Unmounting and deleting containerd, kubelet, cni, etcd and other kubernetes files and folders"
+echo "-- $HOSTNAME :Unmounting and deleting containerd, kubelet, cni, etcd and other kubernetes files and folders"
 umount -f /var/run/containerd/*/*/*/* 
 umount -f /var/lib/kubelet/*/*/*/*/* 
 rm -rf /opt/containerd
@@ -800,19 +800,19 @@ rm -f /etc/sysctl.d/98-kubernetes.conf
 sysctl --system 
 sed -i '/.*DNSStubListener=no.*/ c\#DNSStubListener=' /etc/systemd/resolved.conf
 
-echo "-- NODE $i: apt update autoremove autoclean"
+echo "-- $HOSTNAME :apt update autoremove autoclean"
 apt update -y
 apt autoremove -y --purge 
 apt autoclean -y 
 apt clean -y 
 
-echo "-- Node $i: deleting leftover NICs"
+echo "-- $HOSTNAME :deleting leftover NICs"
 for nic in $(ip link show | grep -e lxc -e cali -e cilium -e flannel -e tunl -e cni -e cbr | awk -F@ '{print $1}' | awk '{print $2}'); do
   ip link set $nic down
   ip link delete $nic
 done
 
-echo "-- NODE $i: Uninstall Completed"
+echo "-- $HOSTNAME :Uninstall Completed"
 ____EOF____
     ) &
   done
@@ -846,12 +846,12 @@ ff02::2 ip6-allrouters' >>tmp/hosts
 
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     (
+      echo "-- Updating, upgrading and installing pre-requisites on all nodes, please wait ..." >&3
       IP=${NODE_ARRAY[$i]}
-      echo "-- NODE $i: Updating, upgrading and installing pre-requisites, please wait ..." >&3
       ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
-echo "-- NODE $i: Creating folders and setting permissions"
+echo "-- $HOSTNAME :Creating folders and setting permissions"
 mkdir -p ~/.kube
 mkdir -p /opt/cni/bin
 mkdir -p /run/cni
@@ -863,7 +863,7 @@ chown -R "$(id -un)":"$(id -Gn)" /etc/containerd
 chown -R "$(id -un)":"$(id -Gn)" /run/cni
 chmod -R +r /opt/cni/bin
 
-echo "-- NODE $i: Disabling iptables"
+echo "-- $HOSTNAME :Disabling iptables"
 for cmd in iptables ip6tables iptables-legacy ip6tables-legacy; do
   $cmd-save > /tmp/$cmd-save.txt 
   $cmd -P INPUT ACCEPT 
@@ -882,7 +882,7 @@ for suffex in raw mangle security nat filter; do
 done
 update-alternatives --remove iptables /usr/sbin/iptables-legacy
 
-echo "-- NODE $i: Updating, upgrading and installing pre-requisites, please wait ..."
+echo "-- $HOSTNAME :Updating, upgrading and installing pre-requisites, please wait ..."
 apt update -y 
 apt upgrade -y 
 apt install -y \
@@ -906,7 +906,7 @@ apt install -y \
     cifs-utils \
     openvswitch-switch 
 
-echo "-- NODE $i: Enabling kernel modules, ip forwarding, disabling DNSStubListener and re-link resolv.conf"
+echo "-- $HOSTNAME :Enabling kernel modules, ip forwarding, disabling DNSStubListener and re-link resolv.conf"
 echo 'overlay
 br_netfilter' > /etc/modules-load.d/kubernetes.conf
 modprobe overlay
@@ -928,7 +928,7 @@ systemctl restart systemd-resolved
 echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 apt-get install -y -q
 
-echo "-- NODE $i: Installing gpg for jave (adoptium) and kubernetes"
+echo "-- $HOSTNAME :Installing gpg for jave (adoptium) and kubernetes"
 mkdir -p -m 755 /etc/apt/keyrings
 mkdir -p /etc/apt/sources.list.d/
 mkdir -p /etc/apt/trusted.gpg.d/
@@ -941,14 +941,14 @@ curl --silent -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public
 echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list
 apt update -y 
 
-echo "-- NODE $i: Installing Jave"
+echo "-- $HOSTNAME :Installing Jave"
 apt install -y temurin-21-jre 
 
-echo "-- NODE $i: Installing containerd"
+echo "-- $HOSTNAME :Installing containerd"
 apt install -y containerd
 
 if [ "$i" == "0" ]; then
-  echo "-- NODE $i: Getting latest kubeadm version"
+  echo "-- $HOSTNAME :Getting latest kubeadm version"
   apt-cache policy kubeadm | grep Candidate | awk '{print $2}' > /tmp/K8S_VERSION
 fi
 ____EOF____
@@ -962,13 +962,13 @@ ____EOF____
     readVar K8S_VERSION "$DEFAULT_VERSION" "Please entre k8s version" 1 30
   fi
 
+  echo "-- Installing kubernetes (version: $K8S_VERSION) on all nodes" >&3
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     (
-      echo "-- NODE $i: Installing kubernetes (version: $K8S_VERSION)" >&3
       ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" DEBIAN_FRONTEND="noninteractive" i="$i" K8S_VERSION="$K8S_VERSION" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
-echo "-- NODE $i: Installing kubernetes (version: $K8S_VERSION)"
+echo "-- $HOSTNAME :Installing kubernetes (version: $K8S_VERSION)"
 apt install -y --allow-change-held-packages kubelet=$K8S_VERSION kubeadm=$K8S_VERSION kubectl=$K8S_VERSION 
 apt-mark hold kubelet kubeadm kubectl containerd  
 sh -c "containerd config default > /etc/containerd/config.toml"  
@@ -977,7 +977,7 @@ systemctl daemon-reload
 systemctl enable --now kubelet.service
 systemctl enable --now containerd.service
 
-echo "-- NODE $i: Pulling kubernetes images"
+echo "-- $HOSTNAME :Pulling kubernetes images"
 kubeadm config images pull --kubernetes-version $(echo "$K8S_VERSION" | sed 's/-[0-9].*//')
 ____EOF____
     ) &
@@ -993,15 +993,15 @@ function step2() {
   ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" DEBIAN_FRONTEND="noninteractive" i="$i" CLUSTER_CIDR_FIRST_TWO_OCTETS="$CLUSTER_CIDR_FIRST_TWO_OCTETS" MASTER_IP="${NODE_ARRAY[0]}" K8S_VERSION="$K8S_VERSION" SSH_USERNAME="$SSH_USERNAME" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
-echo "-- NODE $i: Initializing k8s master version: $(echo "$K8S_VERSION" | sed 's/-[0-9].*//')"
+echo "-- $HOSTNAME :Initializing k8s master version: $(echo "$K8S_VERSION" | sed 's/-[0-9].*//')"
 kubeadm init  --kubernetes-version $(echo "$K8S_VERSION" | sed 's/-[0-9].*//') \
               --apiserver-advertise-address=$MASTER_IP \
               --pod-network-cidr=${CLUSTER_CIDR_FIRST_TWO_OCTETS}.0.0/16
 
-echo "-- NODE $i: Creating join.sh"
+echo "-- $HOSTNAME :Creating join.sh"
 kubeadm token create --print-join-command > ~/.kube/join.sh
 
-echo "-- NODE $i: Auto kill stuck failed pods every 10 minutes"
+echo "-- $HOSTNAME :Auto kill stuck failed pods every 10 minutes"
 cat <<'EOF' >/etc/systemd/system/kill-failed-pods
 #!/bin/bash
 while true; do
@@ -1033,8 +1033,8 @@ ____EOF____
   echo "-- Copying kubeconfig" >&3
   rm -f $KUBECONFIG
   copyKubeconfig
+  echo "-- Copying kubeconfig to all nodes" >&3
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
-    echo "-- NODE $i: Copying kubeconfig to ~/.kube/config" >&3
     (scp -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$KUBECONFIG" "$SSH_USERNAME"@"${NODE_ARRAY[$i]}":~/.kube/config) &
   done
   wait $!
@@ -1044,17 +1044,17 @@ ____EOF____
   scp -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[0]}":~/.kube/join.sh tmp/
   chmod +x tmp/join.sh
   for ((i = 1; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
-    echo "-- NODE $i: Joining the cluster" >&3
     (
       IP=${NODE_ARRAY[$i]}
+      echo "-- $IP joining the cluster" >&3
       scp -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS tmp/join.sh "$SSH_USERNAME"@"$IP":~/.kube/join.sh
       ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
 chmod +x $HOME/.kube/join.sh
-echo "-- NODE $i: Joining k8s cluster"
+echo "-- $HOSTNAME :Joining k8s cluster"
 $HOME/.kube/join.sh
-echo "-- NODE $i: Completed"
+echo "-- $HOSTNAME :Completed"
 ____EOF____
     ) &
   done
@@ -1085,14 +1085,14 @@ function step3() {
     kubectl create ns kube-network
     kubectl label --overwrite ns kube-network pod-security.kubernetes.io/enforce=privileged
 
+    echo "-- Creating subnet.env and downloading cni binaries on all nodes" >&3
     for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
-      echo "-- Node $i: Creating subnet.env and downloading cni binaries" >&3
       (
       ssh -i "$MY_PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"${NODE_ARRAY[i]}" i=$i CLUSTER_CIDR_FIRST_TWO_OCTETS=$CLUSTER_CIDR_FIRST_TWO_OCTETS bash <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Iseconds)]  "; set -x' DEBUG
 
-echo "-- Node $i: Creating subnet.env"
+echo "-- $HOSTNAME :Creating subnet.env"
 mkdir -p /run/flannel
 rm -f /run/flannel/subnet.env
 cat << EOF > /run/flannel/subnet.env
@@ -1102,7 +1102,7 @@ FLANNEL_MTU=1450
 FLANNEL_IPMASQ=true
 EOF
 
-echo "-- NODE $i: Downloading CNI binaries cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)-v1.5.0.tgz"
+echo "-- $HOSTNAME :Downloading CNI binaries cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)-v1.5.0.tgz"
 mkdir -p /opt/cni/bin
 curl -s -L "https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.5.0.tgz | tar xzf - -C /opt/cni/bin
 chown -R "$(id -un)":"$(id -Gn)" /opt/cni
@@ -1118,7 +1118,7 @@ ____EOF____
 
     for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
       (
-        echo "-- Node $i: fixing flannel/cni NIC" >&3
+        echo "-- Fixing flannel/cni NIC on all nodes" >&3
         ssh -i "$MY_PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
 #!/bin/bash
 trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Is)]  "; set -x' DEBUG
